# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 22:26
from __future__ import unicode_literals
from django.db import migrations

from html import unescape

def html_unescape(apps, schema_editor):
    Artikel = apps.get_model('artikel', 'Artikel')
    for artikel in Artikel.objects.all():
        artikel.titel = unescape(artikel.titel)
        artikel.text  = unescape(artikel.text)
        artikel.tags  = unescape(artikel.tags)
        artikel.save()

class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(html_unescape),
    ]
