# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_artikel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikel', to=settings.AUTH_USER_MODEL),
        ),
    ]
